name: fsanitize check Test

on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      WOLFMQTT_NO_EXTERNAL_BROKER_TESTS: 1

    steps:
    - name: Install dependencies
      run: |
        # Don't prompt for anything
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        # Install mosquitto
        sudo apt-get install -y mosquitto bubblewrap

    - name: Setup mosquitto broker
      run: |
        # Disable default broker daemon
        sudo service mosquitto stop
        sleep 1

    # This is some debug info useful if something goes wrong
    - name: Show network status
      run: |
        sudo ifconfig
        sudo route
        sudo netstat -tulpan

    - uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl
    - name: wolfssl autogen
      working-directory: ./wolfssl
      run: ./autogen.sh
    - name: wolfssl configure
      working-directory: ./wolfssl
      run: ./configure --enable-enckeys
    - name: wolfssl make
      working-directory: ./wolfssl
      run: make
    - name: wolfssl make install
      working-directory: ./wolfssl
      run: sudo make install
    - uses: actions/checkout@master
    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure CC="gcc -fsanitize=address"
    - name: make
      run: make
    - name: make check
      run: make check

    - name: configure without TLS
      run: ./configure CC="gcc -fsanitize=address" --enable-all --disable-tls
    - name: make
      run: make
    - name: make check
      run: make check

    - name: configure with SN Enabled
      run: ./configure CC="gcc -fsanitize=address" --enable-sn
    - name: make
      run: make
    - name: make check
      run: make check

    - name: configure with Non-Block
      run: ./configure CC="gcc -fsanitize=address" --enable-nonblock CFLAGS="-DWOLFMQTT_TEST_NONBLOCK"
    - name: make
      run: make
    - name: make check
      run: make check

    - name: configure with Non-Block and Multi-threading
      run: ./configure CC="gcc -fsanitize=address" --enable-mt --enable-nonblock CFLAGS="-DWOLFMQTT_TEST_NONBLOCK"
    - name: make
      run: make
    - name: make check
      run: make check

      # capture logs on failure
    - name: Show logs on failure
      if: failure() || cancelled()
      run: |
        cat test-suite.log
        cat scripts/*.log
